server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shopperaDB;DB_CLOSE_DELAY=-1
    username: sa
    password:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  signing:
    key: ymLTU8rq83ymLTU8rq83ymLTU8rq83ymLTU8rq83ymLTU8rq83