server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: shoppera
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shopperaDB;DB_CLOSE_DELAY=-1
    username: sa
    password:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  order.notifications.exchange: order-notifications-exchange
  order.notifications.routing.key: realtime-notifications
  realtime.order.updates.queue: realtime-order-updates-queue


grpc:
  server:
    port: 9090



springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  signing:
    key: ymLTU8rq83ymLTU8rq83ymLTU8rq83ymLTU8rq83ymLTU8rq83